# Generated by Django 5.2.16 on 2026-08-03 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='category',
            field=models.ForeignKey(blank=True, help_text='The category this package belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packages', to='packages.category', verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='package',
            name='package_type',
            field=models.ForeignKey(blank=True, help_text='The type/duration class of this package', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packages', to='packages.packagetype', verbose_name='Package Type'),
        ),
    ]
