# Generated by Django 5.2.16 on 2026-08-03 22:49

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('category', models.CharField(choices=[('chest', 'Chest'), ('back', 'Back'), ('shoulders', 'Shoulders'), ('legs', 'Legs'), ('arms', 'Arms'), ('core', 'Core'), ('cardio', 'Cardio'), ('full_body', 'Full Body'), ('stretching', 'Stretching')], default='full_body', max_length=30, verbose_name='Category')),
                ('primary_muscle', models.CharField(blank=True, max_length=100, verbose_name='Primary Muscle')),
                ('secondary_muscles', models.CharField(blank=True, help_text='Comma-separated list of secondary muscles', max_length=300, verbose_name='Secondary Muscles')),
                ('equipment', models.CharField(blank=True, max_length=150, verbose_name='Equipment')),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], default='beginner', max_length=20, verbose_name='Difficulty')),
                ('instructions', models.TextField(blank=True, verbose_name='Instructions')),
                ('common_mistakes', models.TextField(blank=True, verbose_name='Common Mistakes')),
                ('tips', models.TextField(blank=True, verbose_name='Tips')),
                ('image', models.ImageField(blank=True, null=True, upload_to='exercises/', verbose_name='Image')),
                ('video_url', models.URLField(blank=True, verbose_name='Video Demonstration')),
                ('is_bookmarked', models.BooleanField(default=False, verbose_name='Bookmarked')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Exercise',
                'verbose_name_plural': 'Exercises',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['category', 'primary_muscle'], name='workouts_ex_categor_2d5c1f_idx')],
            },
        ),
        migrations.CreateModel(
            name='PersonalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise', models.CharField(max_length=200, verbose_name='Exercise')),
                ('record_type', models.CharField(choices=[('bench_press', 'Bench Press'), ('squat', 'Squat'), ('deadlift', 'Deadlift'), ('overhead_press', 'Overhead Press'), ('run', 'Fastest Run'), ('volume', 'Most Training Volume'), ('duration', 'Longest Workout'), ('streak', 'Most Consecutive Workout Days'), ('custom', 'Custom')], default='custom', max_length=30, verbose_name='Record Type')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Weight (kg)')),
                ('reps', models.PositiveIntegerField(blank=True, null=True, verbose_name='Repetitions')),
                ('time_seconds', models.PositiveIntegerField(blank=True, null=True, verbose_name='Time (Seconds)')),
                ('volume', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Volume')),
                ('achieved_date', models.DateField(auto_now_add=True, verbose_name='Achieved Date')),
                ('is_current', models.BooleanField(default=True, verbose_name='Is Current PR')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_records', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Personal Record',
                'verbose_name_plural': 'Personal Records',
                'ordering': ['-achieved_date'],
            },
        ),
        migrations.CreateModel(
            name='WearableDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_type', models.CharField(choices=[('apple_watch', 'Apple Watch'), ('garmin', 'Garmin'), ('fitbit', 'Fitbit'), ('whoop', 'Whoop'), ('samsung', 'Samsung Health'), ('google_fit', 'Google Fit'), ('polar', 'Polar'), ('other', 'Other')], default='other', max_length=30, verbose_name='Device Type')),
                ('name', models.CharField(max_length=150, verbose_name='Device Name')),
                ('provider', models.CharField(blank=True, max_length=100, verbose_name='Provider')),
                ('access_token', models.CharField(blank=True, max_length=500, verbose_name='Access Token')),
                ('refresh_token', models.CharField(blank=True, max_length=500, verbose_name='Refresh Token')),
                ('is_connected', models.BooleanField(default=True, verbose_name='Connected')),
                ('last_synced', models.DateTimeField(blank=True, null=True, verbose_name='Last Synced')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wearable_devices', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Wearable Device',
                'verbose_name_plural': 'Wearable Devices',
            },
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Workout Name')),
                ('date', models.DateField(verbose_name='Date')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='Start Time')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='End Time')),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Duration (Minutes)')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('muscle_group', models.CharField(blank=True, choices=[('chest', 'Chest'), ('back', 'Back'), ('shoulders', 'Shoulders'), ('legs', 'Legs'), ('arms', 'Arms'), ('core', 'Core'), ('cardio', 'Cardio'), ('full_body', 'Full Body')], max_length=30, verbose_name='Muscle Group')),
                ('workout_type', models.CharField(choices=[('strength', 'Strength'), ('cardio', 'Cardio'), ('hiit', 'HIIT'), ('flexibility', 'Flexibility'), ('endurance', 'Endurance'), ('mixed', 'Mixed')], default='strength', max_length=20, verbose_name='Workout Type')),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='planned', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workouts', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Workout',
                'verbose_name_plural': 'Workouts',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_name', models.CharField(max_length=200, verbose_name='Exercise Name')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('exercise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workout_entries', to='workouts.exercise', verbose_name='Library Exercise')),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='workouts.workout', verbose_name='Workout')),
            ],
            options={
                'verbose_name': 'Workout Exercise',
                'verbose_name_plural': 'Workout Exercises',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Goal Name')),
                ('metric', models.CharField(choices=[('weekly_sessions', 'Weekly Sessions'), ('training_volume', 'Training Volume'), ('weight', 'Body Weight'), ('bmi', 'BMI'), ('distance', 'Distance'), ('custom', 'Custom')], default='custom', max_length=30, verbose_name='Metric')),
                ('target_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Target Value')),
                ('current_value', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Current Value')),
                ('unit', models.CharField(blank=True, default='sessions', max_length=40, verbose_name='Unit')),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('missed', 'Missed')], default='active', max_length=20, verbose_name='Status')),
                ('target_date', models.DateField(blank=True, null=True, verbose_name='Target Date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_goals', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Workout Goal',
                'verbose_name_plural': 'Workout Goals',
            },
        ),
        migrations.CreateModel(
            name='WorkoutPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(blank=True, max_length=500, verbose_name='Caption')),
                ('like_count', models.PositiveIntegerField(default=0, verbose_name='Likes')),
                ('is_public', models.BooleanField(default=True, verbose_name='Public')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_posts', to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='workouts.workout', verbose_name='Workout')),
            ],
            options={
                'verbose_name': 'Workout Post',
                'verbose_name_plural': 'Workout Posts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutPostComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500, verbose_name='Comment')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='workouts.workoutpost', verbose_name='Post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_comments', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Workout Post Comment',
                'verbose_name_plural': 'Workout Post Comments',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutPostLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='workouts.workoutpost', verbose_name='Post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_post_likes', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Workout Post Like',
                'verbose_name_plural': 'Workout Post Likes',
            },
        ),
        migrations.CreateModel(
            name='WorkoutSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_number', models.PositiveIntegerField(default=1, verbose_name='Set Number')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Weight Used')),
                ('reps', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Repetitions')),
                ('rest_time', models.PositiveIntegerField(blank=True, null=True, verbose_name='Rest Time (Seconds)')),
                ('rpe', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='RPE (Rate of Perceived Exertion)')),
                ('notes', models.CharField(blank=True, max_length=300, verbose_name='Notes')),
                ('workout_exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='workouts.workoutexercise', verbose_name='Workout Exercise')),
            ],
            options={
                'verbose_name': 'Workout Set',
                'verbose_name_plural': 'Workout Sets',
                'ordering': ['set_number', 'id'],
            },
        ),
        migrations.CreateModel(
            name='BodyMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Weight (kg)')),
                ('height_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Height (cm)')),
                ('body_fat_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(70)], verbose_name='Body Fat (%)')),
                ('chest_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Chest (cm)')),
                ('waist_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Waist (cm)')),
                ('arm_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Arm Size (cm)')),
                ('leg_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Leg Size (cm)')),
                ('bmi', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='BMI')),
                ('notes', models.CharField(blank=True, max_length=300, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='body_measurements', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Body Measurement',
                'verbose_name_plural': 'Body Measurements',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['user', 'date'], name='workouts_bo_user_id_6f392d_idx')],
            },
        ),
        migrations.CreateModel(
            name='WearableData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(blank=True, max_length=100, verbose_name='Source')),
                ('date', models.DateField(verbose_name='Date')),
                ('heart_rate', models.PositiveIntegerField(blank=True, null=True, verbose_name='Heart Rate (bpm)')),
                ('calories', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Calories Burned')),
                ('steps', models.PositiveIntegerField(blank=True, null=True, verbose_name='Steps')),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True, verbose_name='Workout Duration (min)')),
                ('distance_km', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Distance (km)')),
                ('avg_pace', models.CharField(blank=True, max_length=20, verbose_name='Average Pace')),
                ('active_minutes', models.PositiveIntegerField(blank=True, null=True, verbose_name='Active Minutes')),
                ('sleep_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Sleep (Hours)')),
                ('sync_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Sync Timestamp')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wearable_data', to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='data_points', to='workouts.wearabledevice', verbose_name='Device')),
            ],
            options={
                'verbose_name': 'Wearable Data',
                'verbose_name_plural': 'Wearable Data',
                'ordering': ['-date'],
                'unique_together': {('user', 'device', 'date')},
            },
        ),
        migrations.AddIndex(
            model_name='workout',
            index=models.Index(fields=['user', 'date'], name='workouts_wo_user_id_f1c995_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='workoutpostlike',
            unique_together={('user', 'post')},
        ),
    ]
